# ---------- Stage 1: Install dependencies ---------- only for worker
FROM node:20-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm install

# ---------- Stage 2: Prepare application ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .


RUN npx prisma generate

# ---------- Stage 3: Production runtime ----------
FROM node:20-alpine

WORKDIR /app


RUN npm install -g tsx


COPY --from=builder /app .

CMD ["npm", "run", "worker"]